services:
  db:
    image: postgres
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - db